# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!
target 'Prelens-jinny' do
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'SwiftyJSON'
  pod 'Action'
  pod 'JTAppleCalendar'
  pod 'SDWebImage'
  pod 'UIScrollView-InfiniteScroll'
  pod 'IQKeyboardManagerSwift'
  pod 'KeychainSwift'
  pod 'PKHUD'
  pod 'AlamofireObjectMapper'

  target 'Prelens-jinnyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
